;; -*- mode: eask; lexical-binding: t -*-

(package "eglot-signature"
         "0.1.2"
         "Signature help for Eglot")

(website-url "https://github.com/zsxh/eglot-signature")
(keywords "eglot" "signature" "tools")

(package-file "eglot-signature.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "nongnu")
(source "melpa")

(depends-on "emacs" "30.1")
(depends-on "compat" "30.1.0.0")
(depends-on "eglot" "1.17.30")
(depends-on "jsonrpc" "1.0.24")
